version: '3.3'

services:
  opa:
    image: openpolicyagent/opa
    volumes:
      - ./data/config.yaml:/config.yaml
    command:
      - "run"
      - "--server"
      - "--config-file=config.yaml"
      # - "--log-level=debug"
      - "--log-format=json-pretty"
    ports:
      - "8181:8181"

  nginx:
    image: nginx:alpine
    volumes:
      - ./data:/usr/share/nginx/html

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
